--------------------------------------------------------
--  File created - Tuesday-November-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANIMAUX
--------------------------------------------------------

  CREATE TABLE "SLAH"."ANIMAUX" 
   (	"REFERENCE" NUMBER, 
	"NAISSANCE" NUMBER, 
	"ETAT_SANITAIRE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ETAT_CAGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "SLAH"."CLIENT" 
   (	"ID_C" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"NUM_TEL" NUMBER, 
	"MATRICULE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SLAH"."EMPLOYE" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"MATRICULE_D" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER_A
--------------------------------------------------------

  CREATE TABLE "SLAH"."GERER_A" 
   (	"REFERENCE" NUMBER, 
	"MATRICULE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER_P
--------------------------------------------------------

  CREATE TABLE "SLAH"."GERER_P" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"REF_PLANTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLANTE
--------------------------------------------------------

  CREATE TABLE "SLAH"."PLANTE" 
   (	"REF_PLANTE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"ETAT_PLANTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "SLAH"."PRODUIT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"ID_C" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKETS
--------------------------------------------------------

  CREATE TABLE "SLAH"."TICKETS" 
   (	"NUMTICKET" NUMBER, 
	"PRIX" NUMBER, 
	"DATET" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"ID_C" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENDREP
--------------------------------------------------------

  CREATE TABLE "SLAH"."VENDREP" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SLAH.ANIMAUX
SET DEFINE OFF;
REM INSERTING into SLAH.CLIENT
SET DEFINE OFF;
REM INSERTING into SLAH.EMPLOYE
SET DEFINE OFF;
REM INSERTING into SLAH.GERER_A
SET DEFINE OFF;
REM INSERTING into SLAH.GERER_P
SET DEFINE OFF;
REM INSERTING into SLAH.PLANTE
SET DEFINE OFF;
REM INSERTING into SLAH.PRODUIT
SET DEFINE OFF;
Insert into SLAH.PRODUIT (ID,NOM,TYPE,CATEGORY,PRIX,ID_C) values ('aa','bb','cc','dd',456,null);
REM INSERTING into SLAH.TICKETS
SET DEFINE OFF;
REM INSERTING into SLAH.VENDREP
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ANIMAUX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."PK_ANIMAUX" ON "SLAH"."ANIMAUX" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."PK_CLIENT" ON "SLAH"."CLIENT" ("ID_C") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."PK_EMPLOYE" ON "SLAH"."EMPLOYE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER_A_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."GERER_A_PK" ON "SLAH"."GERER_A" ("REFERENCE", "MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER_P_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."GERER_P_PK" ON "SLAH"."GERER_P" ("MATRICULE", "REF_PLANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PLANTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."PK_PLANTE" ON "SLAH"."PLANTE" ("REF_PLANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."PK_PRODUCT" ON "SLAH"."PRODUIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TICKETS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."PK_TICKETS" ON "SLAH"."TICKETS" ("NUMTICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VENDREP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SLAH"."VENDREP_PK" ON "SLAH"."VENDREP" ("MATRICULE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANIMAUX
--------------------------------------------------------

  ALTER TABLE "SLAH"."ANIMAUX" ADD CONSTRAINT "PK_ANIMAUX" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."ANIMAUX" MODIFY ("ETAT_CAGE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."ANIMAUX" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."ANIMAUX" MODIFY ("ETAT_SANITAIRE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."ANIMAUX" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SLAH"."CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("ID_C")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."CLIENT" MODIFY ("NUM_TEL" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."CLIENT" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."CLIENT" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."CLIENT" MODIFY ("ID_C" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SLAH"."EMPLOYE" ADD CONSTRAINT "PK_EMPLOYE" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."EMPLOYE" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."EMPLOYE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."EMPLOYE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER_A
--------------------------------------------------------

  ALTER TABLE "SLAH"."GERER_A" ADD CONSTRAINT "GERER_A_PK" PRIMARY KEY ("REFERENCE", "MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."GERER_A" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."GERER_A" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER_P
--------------------------------------------------------

  ALTER TABLE "SLAH"."GERER_P" ADD CONSTRAINT "GERER_P_PK" PRIMARY KEY ("MATRICULE", "REF_PLANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."GERER_P" MODIFY ("REF_PLANTE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."GERER_P" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANTE
--------------------------------------------------------

  ALTER TABLE "SLAH"."PLANTE" ADD CONSTRAINT "PK_PLANTE" PRIMARY KEY ("REF_PLANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."PLANTE" MODIFY ("REF_PLANTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "SLAH"."PRODUIT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."PRODUIT" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."PRODUIT" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."PRODUIT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."PRODUIT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."PRODUIT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "SLAH"."TICKETS" ADD CONSTRAINT "PK_TICKETS" PRIMARY KEY ("NUMTICKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."TICKETS" MODIFY ("NUMTICKET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENDREP
--------------------------------------------------------

  ALTER TABLE "SLAH"."VENDREP" ADD CONSTRAINT "VENDREP_PK" PRIMARY KEY ("MATRICULE", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLAH"."VENDREP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SLAH"."VENDREP" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SLAH"."CLIENT" ADD CONSTRAINT "CLIENT_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "SLAH"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SLAH"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "SLAH"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER_A
--------------------------------------------------------

  ALTER TABLE "SLAH"."GERER_A" ADD CONSTRAINT "GERERA_FK1" FOREIGN KEY ("REFERENCE")
	  REFERENCES "SLAH"."ANIMAUX" ("REFERENCE") ENABLE;
  ALTER TABLE "SLAH"."GERER_A" ADD CONSTRAINT "GERERA_FK2" FOREIGN KEY ("MATRICULE")
	  REFERENCES "SLAH"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER_P
--------------------------------------------------------

  ALTER TABLE "SLAH"."GERER_P" ADD CONSTRAINT "GERER_P_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "SLAH"."EMPLOYE" ("MATRICULE") ENABLE;
  ALTER TABLE "SLAH"."GERER_P" ADD CONSTRAINT "GERER_P_FK2" FOREIGN KEY ("REF_PLANTE")
	  REFERENCES "SLAH"."PLANTE" ("REF_PLANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "SLAH"."PRODUIT" ADD CONSTRAINT "FK_CLIENT" FOREIGN KEY ("ID_C")
	  REFERENCES "SLAH"."CLIENT" ("ID_C") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "SLAH"."TICKETS" ADD CONSTRAINT "TICKETS_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "SLAH"."EMPLOYE" ("MATRICULE") ENABLE;
  ALTER TABLE "SLAH"."TICKETS" ADD CONSTRAINT "TICKETS_FK2" FOREIGN KEY ("ID_C")
	  REFERENCES "SLAH"."CLIENT" ("ID_C") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENDREP
--------------------------------------------------------

  ALTER TABLE "SLAH"."VENDREP" ADD CONSTRAINT "VENDREP_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "SLAH"."EMPLOYE" ("MATRICULE") ENABLE;
  ALTER TABLE "SLAH"."VENDREP" ADD CONSTRAINT "VENDREP_FK2" FOREIGN KEY ("ID")
	  REFERENCES "SLAH"."PRODUIT" ("ID") ENABLE;